version: "3"

services:
  server:
    build:
      dockerfile: Dockerfile-server
      context: .
#    command: go run app/server/main.go
    ports:
      - 9081:9081
    networks:
      - outside
      - default

  client:
    build:
      dockerfile: Dockerfile-client
      context: .
#    command: go run app/client/main.go
    depends_on:
      - server
    networks:
      - outside
      - default

networks:
  outside:
    external: true