version: "3"

services:
  server:
    build:
      dockerfile: Dockerfile-server
      context: .
    ports:
      - 9081:9081
    networks:
      - outside
      - default

  client:
    build:
      dockerfile: Dockerfile-client
      context: .
    depends_on:
      - server
    networks:
      - outside
      - default

networks:
  outside:
    external: true