FROM golang:1.18

RUN mkdir -p /app/client

ADD cmd/client /app/client/cmd
ADD pb /app/client/pb
ADD go.mod /app/client
ADD go.sum /app/client

WORKDIR /app/client/cmd

RUN go build -o client

CMD ["./client"]
