FROM golang:1.18

RUN mkdir -p /app/server

ADD cmd/server /app/server/cmd
ADD pb /app/server/pb
ADD go.mod /app/server
ADD go.sum /app/server

WORKDIR /app/server/cmd

RUN go build -o server

CMD ["./server"]
